-- Create a table for tasks
-- Compatible con PostgreSQL / Supabase

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('todo', 'in-progress', 'done')),
  position DOUBLE PRECISION DEFAULT 0 NOT NULL
);

-- Habilitar Realtime
alter publication supabase_realtime add table tasks;

-- Row Level Security (RLS)
alter table tasks enable row level security;
create policy "Enable read access for all users" on tasks for select using (true);
create policy "Enable insert access for all users" on tasks for insert with check (true);
create policy "Enable update access for all users" on tasks for update using (true);
create policy "Enable delete access for all users" on tasks for delete using (true);
